title: Terre & Céramique de Cornouaille
tagLine: L'association a pour objet de promouvoir en Cornouaille, la région de Concarneau, le travail de l’argile sous toutes ses formes, en modelage, tournage, sculpture, et tous types de cuisson (gaz, électrique, bois, raku).
description: Bienvenue sur le site de l'association.
url: https://www.terre-ceramique.fr
lang: fr
locale: fr_FR
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
